server:
  port: 8082

spring:
  application:
    name: compte-transaction

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "default"

  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/compte_transaction_bd?useSSL=false&serverTimezone=UTC
      username: root
      password:
      # JPA properties
  jpa:
      hibernate:
        ddl-auto: update # When you launch the application for the first time - switch "none" at "create"

      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect
      open-in-view: false
      generate-ddl: true

topic:
  name: compte-event-topic

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

